services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dummy-rest-api
    ports:
      - "8000:8000"
    environment:
      - GO_ENV=production
    restart: unless-stopped
